#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v17
# autospec commit: 356da62
#
%define keepstatic 1
Name     : postgis
Version  : 3.4.2
Release  : 53
URL      : https://download.osgeo.org/postgis/source/postgis-3.4.2.tar.gz
Source0  : https://download.osgeo.org/postgis/source/postgis-3.4.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-1-Clause BSD-3-Clause BSL-1.0 CC-BY-2.5 GPL-2.0 HPND ISC MIT
Requires: postgis-bin = %{version}-%{release}
Requires: postgis-data = %{version}-%{release}
Requires: postgis-lib = %{version}-%{release}
Requires: postgis-license = %{version}-%{release}
Requires: postgis-man = %{version}-%{release}
BuildRequires : ImageMagick
BuildRequires : SFCGAL-dev
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : gdal-dev
BuildRequires : geos-dev
BuildRequires : grep
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(cunit)
BuildRequires : pkgconfig(json-c)
BuildRequires : pkgconfig(libpcre2-8)
BuildRequires : pkgconfig(libprotobuf-c)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(proj)
BuildRequires : postgresql-dev
BuildRequires : proj-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
PostGIS adds support for geographic objects to the PostgreSQL object-relational
database. In effect, PostGIS "spatially enables" the PostgreSQL server,
allowing it to be used as a backend spatial database for geographic information
systems (GIS), much like ESRI's SDE or Oracle's Spatial extension. PostGIS
follows the OpenGIS "Simple Features Specification for SQL" and has been
certified as compliant with the "Types and Functions" profile.

%package bin
Summary: bin components for the postgis package.
Group: Binaries
Requires: postgis-data = %{version}-%{release}
Requires: postgis-license = %{version}-%{release}

%description bin
bin components for the postgis package.


%package data
Summary: data components for the postgis package.
Group: Data

%description data
data components for the postgis package.


%package doc
Summary: doc components for the postgis package.
Group: Documentation
Requires: postgis-man = %{version}-%{release}

%description doc
doc components for the postgis package.


%package lib
Summary: lib components for the postgis package.
Group: Libraries
Requires: postgis-data = %{version}-%{release}
Requires: postgis-license = %{version}-%{release}

%description lib
lib components for the postgis package.


%package license
Summary: license components for the postgis package.
Group: Default

%description license
license components for the postgis package.


%package man
Summary: man components for the postgis package.
Group: Default

%description man
man components for the postgis package.


%prep
%setup -q -n postgis-3.4.2
cd %{_builddir}/postgis-3.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722365869
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure
make  %{?_smp_mflags}

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722365869
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/postgis
cp %{_builddir}/postgis-%{version}/COPYING %{buildroot}/usr/share/package-licenses/postgis/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/postgis-%{version}/deps/flatgeobuf/include/flatbuffers/LICENSE %{buildroot}/usr/share/package-licenses/postgis/abb8eb20f7f319cd8b292cdccce15826bac01363 || :
cp %{_builddir}/postgis-%{version}/deps/ryu/LICENSE-Apache2 %{buildroot}/usr/share/package-licenses/postgis/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/postgis-%{version}/deps/ryu/LICENSE-Boost %{buildroot}/usr/share/package-licenses/postgis/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/postgis-%{version}/deps/uthash/LICENSE %{buildroot}/usr/share/package-licenses/postgis/ed99ab11368da07bba91b30f8289f5efe6175565 || :
cp %{_builddir}/postgis-%{version}/deps/wagyu/LICENSE.geometry %{buildroot}/usr/share/package-licenses/postgis/25c0e2ad5263cedb0cfd7e6aebc2ee2c55735d5d || :
cp %{_builddir}/postgis-%{version}/deps/wagyu/LICENSE.wagyu %{buildroot}/usr/share/package-licenses/postgis/f92a1c30c362beedbe56ef26dbe375917a0b3089 || :
cp %{_builddir}/postgis-%{version}/doc/xsl/LICENSE %{buildroot}/usr/share/package-licenses/postgis/e501a1902bfc6bb496ad5d2fc66e0a758ed03bb0 || :
cp %{_builddir}/postgis-%{version}/extensions/address_standardizer/COPYING %{buildroot}/usr/share/package-licenses/postgis/72a08efb60f0505073eef690c6612036bd7e0697 || :
cp %{_builddir}/postgis-%{version}/extras/tiger_geocoder/COPYING %{buildroot}/usr/share/package-licenses/postgis/dc8f2e570bf431427dbc3bab9d4d551b53a60208 || :
cp %{_builddir}/postgis-%{version}/postgis/geobuf.LICENSE %{buildroot}/usr/share/package-licenses/postgis/05978e722bceaa08bb8055ceb48906cee1a55687 || :
cp %{_builddir}/postgis-%{version}/postgis/vector_tile.LICENSE %{buildroot}/usr/share/package-licenses/postgis/644a450c6de6d9bd6f346b08a5fc35c887a22847 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pgsql2shp
/usr/bin/pgtopo_export
/usr/bin/pgtopo_import
/usr/bin/postgis
/usr/bin/postgis_restore
/usr/bin/raster2pgsql
/usr/bin/shp2pgsql

%files data
%defattr(-,root,root,-)
/usr/share/postgresql/contrib/postgis-3.4/legacy.sql
/usr/share/postgresql/contrib/postgis-3.4/legacy_gist.sql
/usr/share/postgresql/contrib/postgis-3.4/legacy_minimal.sql
/usr/share/postgresql/contrib/postgis-3.4/postgis.sql
/usr/share/postgresql/contrib/postgis-3.4/postgis_comments.sql
/usr/share/postgresql/contrib/postgis-3.4/postgis_upgrade.sql
/usr/share/postgresql/contrib/postgis-3.4/raster_comments.sql
/usr/share/postgresql/contrib/postgis-3.4/rtpostgis.sql
/usr/share/postgresql/contrib/postgis-3.4/rtpostgis_legacy.sql
/usr/share/postgresql/contrib/postgis-3.4/rtpostgis_upgrade.sql
/usr/share/postgresql/contrib/postgis-3.4/sfcgal.sql
/usr/share/postgresql/contrib/postgis-3.4/sfcgal_comments.sql
/usr/share/postgresql/contrib/postgis-3.4/sfcgal_upgrade.sql
/usr/share/postgresql/contrib/postgis-3.4/spatial_ref_sys.sql
/usr/share/postgresql/contrib/postgis-3.4/topology.sql
/usr/share/postgresql/contrib/postgis-3.4/topology_comments.sql
/usr/share/postgresql/contrib/postgis-3.4/topology_upgrade.sql
/usr/share/postgresql/contrib/postgis-3.4/uninstall_legacy.sql
/usr/share/postgresql/contrib/postgis-3.4/uninstall_postgis.sql
/usr/share/postgresql/contrib/postgis-3.4/uninstall_rtpostgis.sql
/usr/share/postgresql/contrib/postgis-3.4/uninstall_sfcgal.sql
/usr/share/postgresql/contrib/postgis-3.4/uninstall_topology.sql
/usr/share/postgresql/extension/address_standardizer--1.0--3.4.2.sql
/usr/share/postgresql/extension/address_standardizer--2.0.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.0.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.0.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.0.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.0.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.0.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.0.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.0.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.1.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.2.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.11--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.3.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.4.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer--2.5.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.0.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.1.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.2.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.2.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.2.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.2.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.2.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.2.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.2.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.3.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.3.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.3.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.3.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.3.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.3.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.4.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.4.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.4.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer--3.4.2.sql
/usr/share/postgresql/extension/address_standardizer--ANY--3.4.2.sql
/usr/share/postgresql/extension/address_standardizer--TEMPLATED--TO--ANY.sql
/usr/share/postgresql/extension/address_standardizer.control
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.0.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.1.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.2.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.11--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.3.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.4.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--2.5.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.0.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.10--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.7--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.8--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.1.9--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.2.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.2.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.2.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.2.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.2.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.2.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.2.6--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.3.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.3.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.3.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.3.3--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.3.4--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.3.5--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.4.0--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.4.1--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.4.2--3.4.2next.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.4.2--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.4.2.sql
/usr/share/postgresql/extension/address_standardizer_data_us--3.4.2next--3.4.2.sql
/usr/share/postgresql/extension/address_standardizer_data_us--ANY--3.4.2.sql
/usr/share/postgresql/extension/address_standardizer_data_us--TEMPLATED--TO--ANY.sql
/usr/share/postgresql/extension/address_standardizer_data_us.control
/usr/share/postgresql/extension/postgis--2.0.0--ANY.sql
/usr/share/postgresql/extension/postgis--2.0.1--ANY.sql
/usr/share/postgresql/extension/postgis--2.0.2--ANY.sql
/usr/share/postgresql/extension/postgis--2.0.3--ANY.sql
/usr/share/postgresql/extension/postgis--2.0.4--ANY.sql
/usr/share/postgresql/extension/postgis--2.0.5--ANY.sql
/usr/share/postgresql/extension/postgis--2.0.6--ANY.sql
/usr/share/postgresql/extension/postgis--2.0.7--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.0--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.1--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.2--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.3--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.4--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.5--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.6--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.7--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.8--ANY.sql
/usr/share/postgresql/extension/postgis--2.1.9--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.0--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.1--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.2--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.3--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.4--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.5--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.6--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.7--ANY.sql
/usr/share/postgresql/extension/postgis--2.2.8--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.0--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.1--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.10--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.11--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.2--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.3--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.4--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.5--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.6--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.7--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.8--ANY.sql
/usr/share/postgresql/extension/postgis--2.3.9--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.0--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.1--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.10--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.2--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.3--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.4--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.5--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.6--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.7--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.8--ANY.sql
/usr/share/postgresql/extension/postgis--2.4.9--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.0--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.1--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.2--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.3--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.4--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.5--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.6--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.7--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.8--ANY.sql
/usr/share/postgresql/extension/postgis--2.5.9--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.0--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.1--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.10--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.2--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.3--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.4--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.5--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.6--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.7--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.8--ANY.sql
/usr/share/postgresql/extension/postgis--3.0.9--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.0--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.1--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.10--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.2--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.3--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.4--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.5--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.6--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.7--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.8--ANY.sql
/usr/share/postgresql/extension/postgis--3.1.9--ANY.sql
/usr/share/postgresql/extension/postgis--3.2.0--ANY.sql
/usr/share/postgresql/extension/postgis--3.2.1--ANY.sql
/usr/share/postgresql/extension/postgis--3.2.2--ANY.sql
/usr/share/postgresql/extension/postgis--3.2.3--ANY.sql
/usr/share/postgresql/extension/postgis--3.2.4--ANY.sql
/usr/share/postgresql/extension/postgis--3.2.5--ANY.sql
/usr/share/postgresql/extension/postgis--3.2.6--ANY.sql
/usr/share/postgresql/extension/postgis--3.3.0--ANY.sql
/usr/share/postgresql/extension/postgis--3.3.1--ANY.sql
/usr/share/postgresql/extension/postgis--3.3.2--ANY.sql
/usr/share/postgresql/extension/postgis--3.3.3--ANY.sql
/usr/share/postgresql/extension/postgis--3.3.4--ANY.sql
/usr/share/postgresql/extension/postgis--3.3.5--ANY.sql
/usr/share/postgresql/extension/postgis--3.4.0--ANY.sql
/usr/share/postgresql/extension/postgis--3.4.1--ANY.sql
/usr/share/postgresql/extension/postgis--3.4.2--ANY.sql
/usr/share/postgresql/extension/postgis--3.4.2.sql
/usr/share/postgresql/extension/postgis--ANY--3.4.2.sql
/usr/share/postgresql/extension/postgis--TEMPLATED--TO--ANY.sql
/usr/share/postgresql/extension/postgis--unpackaged--3.4.2.sql
/usr/share/postgresql/extension/postgis--unpackaged.sql
/usr/share/postgresql/extension/postgis.control
/usr/share/postgresql/extension/postgis_raster--2.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.2.8--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.10--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.11--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.8--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.3.9--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.10--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.8--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.4.9--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.8--ANY.sql
/usr/share/postgresql/extension/postgis_raster--2.5.9--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.10--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.8--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.0.9--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.10--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_raster--3.4.2.sql
/usr/share/postgresql/extension/postgis_raster--ANY--3.4.2.sql
/usr/share/postgresql/extension/postgis_raster--TEMPLATED--TO--ANY.sql
/usr/share/postgresql/extension/postgis_raster--unpackaged--3.4.2.sql
/usr/share/postgresql/extension/postgis_raster--unpackaged.sql
/usr/share/postgresql/extension/postgis_raster.control
/usr/share/postgresql/extension/postgis_sfcgal--2.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.2.8--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.10--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.11--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.8--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.3.9--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.10--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.8--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.4.9--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.8--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--2.5.9--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.10--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.8--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.0.9--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.10--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--3.4.2.sql
/usr/share/postgresql/extension/postgis_sfcgal--ANY--3.4.2.sql
/usr/share/postgresql/extension/postgis_sfcgal--TEMPLATED--TO--ANY.sql
/usr/share/postgresql/extension/postgis_sfcgal--unpackaged--3.4.2.sql
/usr/share/postgresql/extension/postgis_sfcgal--unpackaged.sql
/usr/share/postgresql/extension/postgis_sfcgal.control
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.2.8--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.10--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.11--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.8--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.3.9--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.10--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.8--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.4.9--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.8--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--2.5.9--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.10--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.8--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.0.9--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.10--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--3.4.2.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--ANY--3.4.2.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--TEMPLATED--TO--ANY.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder--unpackaged--3.4.2.sql
/usr/share/postgresql/extension/postgis_tiger_geocoder.control
/usr/share/postgresql/extension/postgis_topology--2.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.2.8--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.10--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.11--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.8--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.3.9--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.10--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.8--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.4.9--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.8--ANY.sql
/usr/share/postgresql/extension/postgis_topology--2.5.9--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.10--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.8--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.0.9--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.10--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.7--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.8--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.1.9--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.2.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.2.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.2.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.2.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.2.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.2.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.2.6--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.3.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.3.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.3.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.3.3--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.3.4--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.3.5--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.4.0--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.4.1--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.4.2--ANY.sql
/usr/share/postgresql/extension/postgis_topology--3.4.2.sql
/usr/share/postgresql/extension/postgis_topology--ANY--3.4.2.sql
/usr/share/postgresql/extension/postgis_topology--TEMPLATED--TO--ANY.sql
/usr/share/postgresql/extension/postgis_topology--unpackaged--3.4.2.sql
/usr/share/postgresql/extension/postgis_topology--unpackaged.sql
/usr/share/postgresql/extension/postgis_topology.control

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/postgresql/extension/README.address_standardizer

%files lib
%defattr(-,root,root,-)
/usr/lib64/postgresql/address_standardizer-3.so
/usr/lib64/postgresql/postgis-3.so
/usr/lib64/postgresql/postgis_raster-3.so
/usr/lib64/postgresql/postgis_sfcgal-3.so
/usr/lib64/postgresql/postgis_topology-3.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/postgis/05978e722bceaa08bb8055ceb48906cee1a55687
/usr/share/package-licenses/postgis/25c0e2ad5263cedb0cfd7e6aebc2ee2c55735d5d
/usr/share/package-licenses/postgis/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/postgis/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/postgis/644a450c6de6d9bd6f346b08a5fc35c887a22847
/usr/share/package-licenses/postgis/72a08efb60f0505073eef690c6612036bd7e0697
/usr/share/package-licenses/postgis/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/postgis/abb8eb20f7f319cd8b292cdccce15826bac01363
/usr/share/package-licenses/postgis/dc8f2e570bf431427dbc3bab9d4d551b53a60208
/usr/share/package-licenses/postgis/e501a1902bfc6bb496ad5d2fc66e0a758ed03bb0
/usr/share/package-licenses/postgis/ed99ab11368da07bba91b30f8289f5efe6175565
/usr/share/package-licenses/postgis/f92a1c30c362beedbe56ef26dbe375917a0b3089

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/pgsql2shp.1
/usr/share/man/man1/pgtopo_export.1
/usr/share/man/man1/pgtopo_import.1
/usr/share/man/man1/postgis.1
/usr/share/man/man1/postgis_restore.1
/usr/share/man/man1/shp2pgsql.1
